name: MAIN FOODGRAM WORKFLOW
on:
  push:
    branches:
      - postman-fixes
jobs:
  checkout-and-print-tree:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Print project tree
        run: tree .
